# LAB 2- Machine learning Use Case-KNN with Iris Dataset 
# 1. Step-by-Step KNN Implementation:
# 2. Import necessary libraries
# 3. Load dataset
# 4. Split the data into training and test sets
# 5. Scale the data
# 6. Train the KNN model
# 7. Evaluate the model

In [3]:
import pandas as pd
import numpy as np


In [5]:
#read dataset stored in path Data
data = pd.read_csv('Data/Iris_data.csv')

In [13]:
#print iris 
print(data)

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]


In [9]:
#count species in iris
data.species.value_counts()

species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [11]:
#check data type
data.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [22]:
#encode categorical data to numerical data
#in this dataset, species is categorical data -hence need to change tu numerical using albel encoder
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data.species=le.fit_transform(data.species)

In [24]:
# to view the first 5 rows of data in iris
#species has changes to numerical value represented by 0,1 and 2 
data.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [26]:
#to view the last 5 rows
data.tail()

sepal_length  sepal_width  petal_length  petal_width  species
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

# SPLIT BETWEEN TARGET AND FEATURE COLUMNS

In [30]:
#features list
#species will be the target hence we need to drop it from features 
X=data.drop('species', axis=1)
#target-assigned teh target to y 
y=data.species

In [32]:
#print X after drop species 
X

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [36]:
#print y after set as target 
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: species, Length: 150, dtype: int32

# Split the data into training and test sets
At the begining you will split your data into a train and a test set. So you will have X_train and y_train for the features and target values you will use during the training of your model. And you will have X_test and y_test for the features and target values you will use for the final evaluation of your model.

X is a matrix of the features values, each column being one feature, and being known values.

Each column of X is an independant variable.

y is a vector of the target values, being the values you want to try to predict.

y has only one column and is the dependant/target variable.

A row in X anf y is one data sample.

In [40]:
#splitting the dataset into trainning and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=0)#start from 0 -random_state=0 , we get the same train and test sets across different executions.

In [42]:
X_train.shape

(105, 4)

In [44]:
X_train

sepal_length  sepal_width  petal_length  petal_width
60            5.0          2.0           3.5          1.0
116           6.5          3.0           5.5          1.8
144           6.7          3.3           5.7          2.5
119           6.0          2.2           5.0          1.5
108           6.7          2.5           5.8          1.8
..            ...          ...           ...          ...
9             4.9          3.1           1.5          0.1
103           6.3          2.9           5.6          1.8
67            5.8          2.7           4.1          1.0
117           7.7          3.8           6.7          2.2
47            4.6          3.2           1.4          0.2

[105 rows x 4 columns]

In [48]:
X_test.shape

(45, 4)

In [50]:
y_train

60     1
116    2
144    2
119    2
108    2
      ..
9      0
103    2
67     1
117    2
47     0
Name: species, Length: 105, dtype: int32

In [52]:
y_train.shape

(105,)

In [54]:
y_test

114    2
62     1
33     0
107    2
7      0
100    2
40     0
86     1
76     1
71     1
134    2
51     1
73     1
54     1
63     1
37     0
78     1
90     1
45     0
16     0
121    2
66     1
24     0
8      0
126    2
22     0
44     0
97     1
93     1
26     0
137    2
84     1
27     0
127    2
132    2
59     1
18     0
83     1
61     1
92     1
112    2
2      0
141    2
43     0
10     0
Name: species, dtype: int32

# STANDARDIZATION/SCALING
# DISTANCE-BASED Algorithm is sensitive to data distribution. It is necessary to scale the data. Let's try scaling with MinMaxScaler()

In [70]:
#MinMaxScaller will return the data between 0-1
#Transform features by scaling each feature to a given range.
#This estimator scales and translates each feature individually such that it is in the given range on the training set,
#e.g. between zero and one.

#The fit(data) method is used to compute the mean and std dev for a given feature so that it can be used further for scaling.
#The transform(data) method is used to perform scaling using mean and std dev calculated using the .fit() method.
#The fit_transform() method does both fit and transform.

# Fit the scaler on the training data and transform it-for KNN only scale the features(X_train,X_test) not the label/target(y_train,y_test)-label in iris dataset is categorical 0,1,2-no need scaling
# Apply the same transformation to the test data (without fitting again!)-test data is used to test the model -it is unseen data-do not fit the scaler on the test data to avoid data leakage.

from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
X_scale_train=scaler.fit_transform(X_train)
X_scale_train

array([[0.19444444, 0.        , 0.4137931 , 0.375     ],
       [0.61111111, 0.41666667, 0.75862069, 0.70833333],
       [0.66666667, 0.54166667, 0.79310345, 1.        ],
       [0.47222222, 0.08333333, 0.67241379, 0.58333333],
       [0.66666667, 0.20833333, 0.81034483, 0.70833333],
       [0.36111111, 0.20833333, 0.48275862, 0.41666667],
       [0.94444444, 0.41666667, 0.86206897, 0.91666667],
       [0.55555556, 0.54166667, 0.62068966, 0.625     ],
       [0.33333333, 0.16666667, 0.46551724, 0.41666667],
       [0.55555556, 0.29166667, 0.65517241, 0.70833333],
       [0.55555556, 0.33333333, 0.68965517, 0.58333333],
       [0.16666667, 0.20833333, 0.5862069 , 0.66666667],
       [0.55555556, 0.20833333, 0.67241379, 0.75      ],
       [0.75      , 0.5       , 0.62068966, 0.54166667],
       [0.61111111, 0.41666667, 0.70689655, 0.79166667],
       [0.47222222, 0.58333333, 0.5862069 , 0.625     ],
       [0.13888889, 0.45833333, 0.0862069 , 0.04166667],
       [0.41666667, 0.29166667,

In [74]:
# Apply the same transformation to the test data (without fitting again!)-test data is used to test the model -it is unseen data-do not fit the scaler on the test data to avoid data leakage.
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
X_scale_test=scaler.fit_transform(X_test)
X_scale_test

array([[0.48275862, 0.3       , 0.77358491, 0.95833333],
       [0.55172414, 0.        , 0.56603774, 0.375     ],
       [0.37931034, 1.        , 0.0754717 , 0.04166667],
       [1.        , 0.35      , 1.        , 0.70833333],
       [0.20689655, 0.6       , 0.09433962, 0.04166667],
       [0.65517241, 0.55      , 0.94339623, 1.        ],
       [0.20689655, 0.65      , 0.05660377, 0.08333333],
       [0.79310345, 0.45      , 0.69811321, 0.58333333],
       [0.82758621, 0.3       , 0.71698113, 0.54166667],
       [0.5862069 , 0.3       , 0.56603774, 0.5       ],
       [0.5862069 , 0.2       , 0.86792453, 0.54166667],
       [0.68965517, 0.5       , 0.66037736, 0.58333333],
       [0.5862069 , 0.3       , 0.69811321, 0.45833333],
       [0.72413793, 0.3       , 0.67924528, 0.58333333],
       [0.5862069 , 0.35      , 0.69811321, 0.54166667],
       [0.17241379, 0.45      , 0.09433962, 0.        ],
       [0.55172414, 0.35      , 0.66037736, 0.58333333],
       [0.37931034, 0.2       ,

# Fitting and Evaluating the Model
# KNN CLASSIFIER


In [86]:
#The first line creates an instance of the KNeighborsClassifier class with the parameter n_neighbors set to 3.
# This means that the classifier will consider the 3 nearest neighbors when making predictions.
# The second line fits the classifier to the training data X_scale_train and y_train.
#This means that the classifier will learn from the training data(scale) and be able to make predictions on new data.
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
knn = knn.fit(X_scale_train,y_train)



In [88]:
#The knn object is assumed to have been previously defined and trained on a training dataset.
# The predict method of the knn object is then called with the X_test (scale) dataset as input.
# This returns an array of predicted class labels for each sample in X_test, which is assigned to the variable y_pred.
# Overall, this code is used to evaluate the performance of the KNN classifier on a test dataset by comparing the predicted labels to the true labels.
y_pred = knn.predict(X_scale_test)
y_pred 

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2, 1, 1, 2, 0, 2, 0,
       0])

# EVALUATION

In [95]:
from sklearn.metrics import classification_report
#calculates the accuracy of a machine learning model by comparing the predicted values 
#(stored in y_pred) with the actual values (stored in y_test).
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9777777777777777

In [93]:
#A classification report is used to measure the quality of predictions from a classification algorithm. 
#It details how many predictions are true and how many are false

from sklearn.metrics import classification_report
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.94      0.97        18
           2       0.92      1.00      0.96        11

    accuracy                           0.98        45
   macro avg       0.97      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45

